# Generated by Django 6.0.7 on 2026-09-06 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('source', models.CharField(default='api', max_length=10)),
                ('test_id', models.CharField(blank=True, default='', max_length=10)),
                ('outcome', models.CharField(max_length=20)),
                ('retriever_status', models.CharField(blank=True, default='', max_length=20)),
                ('fallback_reason', models.CharField(blank=True, default='', max_length=50)),
                ('top_score', models.FloatField(blank=True, null=True)),
                ('num_results', models.IntegerField(default=0)),
                ('time_taken_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(blank=True, default='', max_length=30)),
                ('collection_name', models.CharField(max_length=100)),
                ('chunks_indexed', models.IntegerField(blank=True, null=True)),
                ('top_k', models.IntegerField()),
                ('min_score', models.FloatField()),
                ('ambiguous_gap', models.FloatField()),
                ('config_summary', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('chunk_id', models.CharField(blank=True, default='', max_length=50)),
                ('document_id', models.CharField(blank=True, default='', max_length=20)),
                ('policy_title', models.CharField(max_length=200)),
                ('section', models.CharField(blank=True, default='', max_length=200)),
                ('subsection', models.CharField(blank=True, default='', max_length=200)),
                ('source_url', models.CharField(blank=True, default='', max_length=500)),
                ('status_details_url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('effective_date', models.CharField(blank=True, default='', max_length=50)),
                ('score', models.FloatField()),
                ('text_snippet', models.TextField(blank=True, default='')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.auditlog')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
